# Generated by Django 3.1.7 on 2021-03-07 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlePost', models.CharField(max_length=100, verbose_name='Title of Post')),
                ('slugPost', models.CharField(max_length=150, verbose_name='Slug of Post')),
                ('descriptionPost', models.CharField(max_length=200, verbose_name='Description of Post')),
                ('contentsPost', models.TextField(verbose_name='Contents of Post')),
                ('imagePost', models.URLField(max_length=300, verbose_name='URL of Image')),
                ('conditionPost', models.BooleanField(default=True, verbose_name='Publicationed/Not Publicationed')),
                ('createDatePost', models.DateTimeField(auto_now_add=True, verbose_name='Createdate of Post')),
                ('updateDatePost', models.DateTimeField(auto_now=True, verbose_name='Update Date of Post')),
                ('authorPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.author')),
                ('categoryPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogApp.category')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
