# Generated by Django 3.1.7 on 2021-03-07 22:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='contentsPost',
            field=ckeditor.fields.RichTextField(verbose_name='Contents of Post'),
        ),
    ]
